#!/usr/bin/env bash
# Install Nginx with the -y flag for automatic confirmation
apt-get -y update
apt-get install -y nginx

# Ensure Nginx is listening on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

apt-get -y update
apt-get -y install nginx

sudo service nginx start

ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# Restart Nginx without using systemctl
service nginx restart
