#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Create a custom index file if needed
echo "Holberton School" | sudo tee /var/www/html/custom_index.html

# Update the Nginx configuration for redirection
sudo sed -i '/listen 80 default_server/a return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
