#!/usr/bin/env bash
# Script that installs Nginx server and adds a custom 404 not found

# Update package lists and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow Nginx HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

# Create the custom 404 page with the string "Ceci n'est pas une page"
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Define the configuration lines for customizing 404 handling in Nginx
newlines="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"

# Insert the new configuration lines at line 27 in the Nginx configuration file
sudo sed -i "27i $newlines" /etc/nginx/sites-available/default

# Restart Nginx to apply the configuration changes
sudo service nginx restart
