#!/usr/bin/env bash
# Script to install and configure HAproxy on lb-01 server

# Update package lists and Install HAproxy
sudo apt-get -y update
apt-get -y install haproxy

# Backup HAproxy config file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg_backup

# Configure HAproxy
server_config=\
"
frontend  http_frontend
        bind *:80
        mode http
        default_backend http_backend
backend http_backend
        balance roundrobin
        server 524568-web-01 18.204.16.143:80 check
        server 524568-web-02 54.236.53.174:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Test the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg && echo "HAproxy configuration is valid."

# Restart HAproxy
sudo service haproxy restart && echo "HAproxy restarted successfully."
