#!/usr/bin/env bash
# Configures Nginx to listen on port 80 for all of the server's active IPv4 IPs

# Create a symbolic link for the default Nginx site configuration
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply the configuration changes
sudo service restart nginx
