#!/usr/bin/env bash
# Bash script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
# shellcheck disable=SC2009
# The line above disables a specific shellcheck warning (SC2009) for the command substitution in the next line.

# Using ps and grep to find the Bash process
ps aux | grep bash | grep -v grep
