#!/usr/bin/env bash
# Bash script that displays "To infinity and beyond" indefinitely
# with a sleep 2 in between each iteration, and responds to SIGTERM with "I am invincible!!!"


while true; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
