#!/usr/bin/env bash
# Bash script that displays username, user id, and home directory path for users in /etc/passwd

while IFS=':' read -r username _ uid _ _ home _; do
    echo "$username:$uid:$home"
done < /etc/passwd
