#!/usr/bin/env bash
# Bash script to group visitors by IP and HTTP status code from Apache log file and display in specified format using awk

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
