#!/usr/bin/env bash
# This script uses ssh to connect to the server using a private key

# Connect to the server using the private key ~/.ssh/school and the user ubuntu
ssh -i  ~/.ssh/school ubuntu@18.204.16.143
